Repository softeerbootcamp4th/Team9-Podo-FE, pull requests merged in 2024-08, with the labels that each got.

#31 [Chore] msw setting
  .storybook/main.ts
  .storybook/preview.ts
  jest.config.js
  jest.polyfills.js
  package.json
  public/mockServiceWorker.js
  setupTests.ts
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/data/FCFSEvent.ts
  src/mocks/handler/FCFSEvent.ts
  src/mocks/handler/index.ts
  src/mocks/node.ts
  src/pages/FCFSEventPage/FCFSEventPage.stories.tsx
  src/pages/FCFSEventPage/FCFSEventPage.test.tsx
  yarn.lock
Labels: 📬 API, ⚙ Setting

#32 [Feature] event2 quiz section 개발
  src/components/randomEventPage/Option/Option.stories.tsx
  src/components/randomEventPage/Option/Option.test.tsx
  src/components/randomEventPage/Option/Option.tsx
  src/constants/RandomEventData.ts
  src/pages/randomEventPage/RandomQuizSection.stories.tsx
  src/pages/randomEventPage/RandomQuizSection.test.tsx
  src/pages/randomEventPage/RandomQuizSection.tsx
Labels: ✨ Feature, ⚙ Setting, ✅ Test

#37 [Chore] webpack 개발과 배포 버전 설정 파일 분리
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 🌏 Deploy, ⚙ Setting

#43 [Feature] 전역으로 정의된 context 생성
  src/App.tsx
  src/pages/providers     /AppProvider.tsx
Labels: ✨ Feature

#46 [Feature] event2 결과 페이지 결과섹션, 기대평 섹션
  __mocks__/fileMock.ts
  jest.config.js
  package.json
  src/App.tsx
  src/components/common/HomeButton/HomeButton.tsx
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/Toast.test.tsx
  src/components/common/Toast/Toast.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/pages/randomEventResultPage/RandomExpectations.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.stories.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.test.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/pages/randomEventResultPage/RandomMainSection.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.stories.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/providers/AppProvider.tsx
  yarn.lock
Labels: ✨ Feature, ✅ Test, 🎨Style

#47 [Feature] 선착순 이벤트 결과 페이지 및 글로우 컴포넌트 구현
  src/App.tsx
  src/api/fetch.ts
  src/assets/images/FCFSCar.png
  src/assets/images/FCFSKey.png
  src/assets/svg/FCFSKeyButton.tsx
  src/assets/svg/FCFSNoticeBanner.tsx
  src/assets/svg/Glow1.tsx
  src/assets/svg/Glow2.tsx
  src/assets/svg/Glow3.tsx
  src/assets/svg/RefreshButton.tsx
  src/components/common/Glow/Glow.stories.tsx
  src/components/common/Glow/Glow.test.tsx
  src/components/common/Glow/Glow.tsx
  src/constants/FCFSEventResultData.ts
  src/hooks/useAnimation.tsx
  src/mocks/data/FCFSEvent.ts
  src/mocks/handler/FCFSEvent.ts
  src/pages/FCFSEventPage/FCFSEventPage.test.tsx
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/FCFSEventPage/FCFSHintSection.tsx
  src/pages/FCFSEventPage/FCFSQuizSection.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.test.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/styles/keyframes.ts
  src/styles/options.ts
  src/types/FCFSEvent.ts
  tailwind.config.js
Labels: ✨ Feature, ✅ Test

#49 [Feature] event2 result 전환 애니메이션, 기대평 자동 스크롤
  src/index.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
Labels: ✨ Feature

#54 [Feature] 인증모달 테스트, 스타일, 로직 구현 및 선착순 힌트 페이지 수정
  src/api/fetch.ts
  src/components/common/AuthTooltip/AuthTooltip.tsx
  src/constants/AuthModal.ts
  src/hooks/useAnimation.tsx
  src/hooks/useInputs.tsx
  src/hooks/useTimer.tsx
  src/mocks/data/AuthModal.ts
  src/mocks/handler/AuthModal.ts
  src/mocks/handler/FCFSEvent.ts
  src/mocks/handler/index.ts
  src/pages/FCFSEventPage/FCFSHintSection.tsx
  src/pages/authModal/AuthModal.stories.tsx
  src/pages/authModal/AuthModal.test.tsx
  src/pages/authModal/AuthModal.tsx
  src/types/AuthModal.ts
  src/utils/auth.ts
  tailwind.config.js
  webpack.dev.js
Labels: ✨ Feature, ✅ Test, 🎨Style

#52 [Feature] main event selection layout, snap 구현
  src/assets/images/e1Gift.png
  src/assets/images/e2Gift.png
  src/components/mainPage/MainScreen/EventSelectOptions.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.stories.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.test.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.tsx
  src/pages/mainPage/MainScreen/EventSelectSection.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.tsx
  src/pages/mainPage/MainScreen/MainScreen.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.tsx
Labels: ✨ Feature, 🎨Style

#51 [Feature] event2 result api 연결, 기능 마무리
  src/App.test.js
  src/api/post.ts
  src/assets/images/reset.png
  src/assets/images/share.png
  src/components/randomEventPage/Tooltip/Tooltip.stories.tsx
  src/components/randomEventPage/Tooltip/Tooltip.test.tsx
  src/components/randomEventPage/Tooltip/Tooltip.tsx
  src/pages/randomEventPage/RandomEventPage.tsx
  src/pages/randomEventPage/RandomQuizSection.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/types/RandomEvent.ts
  tailwind.config.js
  webpack.dev.js
Labels: ✨ Feature, 📬 API

#57 [Feature] Auth modal 구현
  src/App.tsx
  src/components/common/AuthTooltip/AuthTooltip.test.tsx
  src/components/common/Toast/Toast.test.tsx
  src/components/common/Toast/Toast.tsx
  src/constants/AuthModal.ts
  src/index.tsx
  src/mocks/data/AuthModal.ts
  src/pages/FCFSEventPage/FCFSEventPage.stories.tsx
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.stories.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.test.tsx
  src/pages/authModal/AuthModal.test.tsx
  src/pages/authModal/AuthModal.tsx
  src/pages/mainPage/MainPage.tsx
  src/router/router.tsx
  src/styles/keyframes.ts
  src/styles/options.ts
  src/styles/tailwind.ts
  src/types/tailwind.ts
  src/utils/auth.ts
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: ✨ Feature, 🔨 Refactor

#56 [Feature] Landing 페이지 애니메이션, 섹션 스크롤
  .DS_Store
  src/assets/images/landingCar.png
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.tsx
  src/hooks/useAnimation.tsx
  src/pages/mainPage/LandingScreen/LandingScreen.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/MainScreen/EventSelectSection.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.tsx
  src/pages/mainPage/MainScreen/MainScreen.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨Style

#58 [Feature] glow가 순차적으로 나타나도록 코드 수정
  src/assets/svg/Glow1.tsx
  src/assets/svg/Glow2.tsx
  src/assets/svg/Glow3.tsx
  src/components/common/Glow/Glow.test.tsx
  src/components/common/Glow/Glow.tsx
  src/hooks/useAnimation.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/router/router.tsx
  src/styles/options.ts
Labels: 🎨Style

#60 [Feature] 테스트 코드 수정 및 외장 스크린 구현
  src/assets/images/OutsideInfo.png
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/pages/authModal/AuthModal.tsx
  src/pages/mainPage/InfoScreen/InfoScreen.tsx
  src/pages/mainPage/InfoScreen/OutsideSection.tsx
  src/pages/mainPage/MainScreen/EventSelectSection.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
Labels: ✨ Feature

#61 [Feature] main screen 구조변경, 이벤트 헤더 구현
  src/components/common/GlowBackground/GlowBackground.tsx
  src/components/mainPage/MainScreen/EventHeader.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.stories.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.test.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.tsx
  src/components/mainPage/MainScreen/EvnetHeader.stories.tsx
  src/pages/mainPage/MainScreen/EventSelectSection.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.tsx
  src/pages/mainPage/MainScreen/MainScreen.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨Style

#62 [Feature] main 이벤트 화면 레이아웃, 화면 전환 구현
  src/assets/images/e2Gift1.png
  src/assets/images/e2Gift2.png
  src/assets/images/e2Gift3.png
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.test.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.stories.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.tsx
  src/pages/mainPage/MainScreen/MainScreen.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.stories.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.tsx
Labels: ✨ Feature, 🎨Style

#64 [Feature] main color, performance 데이터 추가
  src/assets/images/colorDarkOceanBlue.png
  src/assets/images/colorFusionBlack.png
  src/assets/images/colorGravityGray.png
  src/assets/images/colorGrean.png
  src/assets/images/colorSnowWhitePearl.png
  src/pages/mainPage/InfoScreen/ColorSection.tsx
  src/pages/mainPage/InfoScreen/InfoScreen.tsx
  src/pages/mainPage/InfoScreen/PerformanceSection.stories.tsx
  src/pages/mainPage/InfoScreen/PerformanceSection.tsx
Labels: ✨ Feature

#65 [Feature] 자동차 스크롤 시 색상이 변경되는 컴포넌트 구현
  src/pages/mainPage/InfoScreen/ColorSection.tsx
  src/pages/mainPage/InfoScreen/PerformanceSection.tsx
Labels: ✨ Feature

#67 [Feature] performance 섹션 구현, useInView 커스텀 훅 제작
  src/assets/images/powerImg.png
  src/constants/InfoData.ts
  src/hooks/useInView.tsx
  src/pages/mainPage/InfoScreen/ConvenienceSection.tsx
  src/pages/mainPage/InfoScreen/DriveSection.tsx
  src/pages/mainPage/InfoScreen/OutsideSection.tsx
  src/pages/mainPage/InfoScreen/PerformanceSection.tsx
Labels: ✨ Feature, 🎨Style

#68 [Feature] 차량 색상 파레트 구현
  src/pages/mainPage/InfoScreen/ColorSection.tsx
  src/pages/mainPage/InfoScreen/VideoSection.tsx
Labels: ✨ Feature

#69 [Refactor] main page
  src/components/common/AuthTooltip/AuthTooltip.stories.tsx
  src/components/common/Button/Button.stories.tsx
  src/components/common/Carousel/Carousel.stories.tsx
  src/components/common/Glow/Glow.stories.tsx
  src/components/common/HomeButton/HomeButton.stories.tsx
  src/components/common/Toast/Toast.stories.tsx
  src/components/mainPage/MainScreen/EventHeader.stories.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.stories.tsx
  src/components/randomEventPage/Option/Option.stories.tsx
  src/components/randomEventPage/ProgressBar/ProgressBar.stories.tsx
  src/components/randomEventPage/Roulette/Roulette.stories.tsx
  src/components/randomEventPage/Tooltip/Tooltip.stories.tsx
  src/constants/EventData.ts
  src/constants/RandomEventData.ts
  src/pages/FCFSEventPage/FCFSEventPage.stories.tsx
  src/pages/FCFSEventPage/FCFSHintSection.stories.tsx
  src/pages/FCFSEventPage/FCFSQuizSection.stories.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.stories.tsx
  src/pages/authModal/AuthModal.stories.tsx
  src/pages/mainPage/InfoScreen/PerformanceSection.stories.tsx
  src/pages/mainPage/MainScreen/EventSelectSection.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.stories.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.stories.tsx
  src/pages/randomEventPage/RandomQuizSection.stories.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.stories.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.stories.tsx
Labels: 🔨 Refactor

#70 [Feature] 내장 소개 기능 구현
  src/assets/images/Interior.png
  src/assets/svg/InnerHighlight.tsx
  src/components/mainPage/InfoScreen/Guide.tsx
  src/components/mainPage/InfoScreen/GuideItem.tsx
  src/constants/InfoData.ts
  src/hooks/useInView.tsx
  src/pages/mainPage/InfoScreen/ConvenienceSection.tsx
  src/pages/mainPage/InfoScreen/DriveSection.tsx
  src/pages/mainPage/InfoScreen/InfoScreen.tsx
  src/pages/mainPage/InfoScreen/InsideSection.tsx
  src/pages/mainPage/InfoScreen/OutsideSection.tsx
  src/types/InfoScreen.ts
Labels: ✨ Feature

#71 [Feature] main event 라우팅, 타이머, ref 오류 수정
  src/components/common/Button/Button.tsx
  src/hooks/useAnimation.tsx
  src/pages/mainPage/InfoScreen/InfoScreen.tsx
  src/pages/mainPage/InfoScreen/VideoSection.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection.tsx
  src/pages/mainPage/MainScreen/MainScreen.tsx
  src/pages/mainPage/MainScreen/RandomEventSection.tsx
  src/pages/mainPage/MainScreen/Timer.tsx
Labels: ✨ Feature

#72 [Feature] word cloud
  package.json
  src/assets/images/.DS_Store
  src/assets/images/wordcloud.png
  src/pages/mainPage/NotificationScreen/NotificationScreen.stories.tsx
  src/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  yarn.lock
Labels: ✨ Feature

#73 [Style] border gradient 뒷 배경이 투명하도록 변경
  src/pages/mainPage/MainScreen/EventSelectSection.tsx
  tailwind.config.js
Labels: 🎨Style

#75 [Feature] api fetch 구현
  src/api/fetch.ts
  src/constants/EventData.ts
  src/pages/authModal/AuthModal.tsx
  src/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/types/FCFSEvent.ts
  src/types/InfoScreen.ts
  src/types/RandomEvent.ts
  src/types/api.ts
Labels: ✨ Feature, 📬 API

#76 [Feature] auth시, 전역 isAuth가 설정되는 기능 구현
  src/api/fetch.ts
  src/pages/FCFSEventPage/FCFSQuizSection.tsx
  src/pages/authModal/AuthModal.tsx
  src/types/AuthModal.ts
Labels: ✨ Feature

#79 [Refactor] 응모 이벤트, 메인 페이지 이벤트 섹션 래픽토링 및 테스트 코드 작성
  src/components/mainPage/InfoScreen/WordCloud.tsx
  src/components/mainPage/MainScreen/EventFooter.tsx
  src/components/mainPage/MainScreen/EventHeader/EventHeader.stories.tsx
  src/components/mainPage/MainScreen/EventHeader/EventHeader.test.tsx
  src/components/mainPage/MainScreen/EventHeader/EventHeader.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.test.tsx
  src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.tsx
  src/components/mainPage/MainScreen/Timer/Timer.tsx
  src/constants/RandomEventData.ts
  src/pages/mainPage/MainScreen/EventSelectSection/EventSelectSection.test.tsx
  src/pages/mainPage/MainScreen/EventSelectSection/EventSelectSection.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.stories.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.test.tsx
  src/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/pages/mainPage/MainScreen/MainScreen.tsx
  src/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.stories.tsx
  src/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.test.tsx
  src/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.tsx
  src/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/pages/randomEventPage/RandomQuizSection.tsx
  src/pages/randomEventPage/RandomQuizSection/RandomQuizSection.stories.tsx
  src/pages/randomEventPage/RandomQuizSection/RandomQuizSection.test.tsx
  src/pages/randomEventPage/RandomQuizSection/RandomQuizSection.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.test.tsx
  src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.stories.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/router/router.tsx
  src/styles/keyframesOptions.ts
  src/styles/tailwind.ts
  src/types/InfoScreen.ts
  src/utils/util.ts
Labels: 🔨 Refactor, ✅ Test

#81 [!HotFix] api 경로 수정
  src/client/api/fetch.ts
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/types/InfoScreen.ts
Labels: 🐞 BugFix

#83 [Feature] admin layout
  src/admin/components/FCFSWinnersPopup/FCFSWinnersPopup.tsx
  src/admin/components/RandomWinnersPopup/RandomWinnersPopup.tsx
  src/admin/pages/CreateEvent/CreateEvent.tsx
  src/admin/pages/EventManagement/EventManagement.tsx
  src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
  src/admin/pages/RandomParticipants/RandomParticipants.tsx
  src/admin/router/router.tsx
Labels: 🎨Style

#84 [Feature] admin 참여자 관리 레이아웃 및 기능
  src/admin/components/FCFSWinnersPopup/FCFSWinnersPopup.tsx
  src/admin/components/RandomWinnersPopup/RandomWinnersPopup.tsx
  src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
  src/admin/pages/RandomParticipants/RandomParticipants.tsx
Labels: ✨ Feature

#85 [Feature] admin 이벤트 관리 레이아웃 및 기능
  src/admin/api/.gitkeep
  src/admin/api/fetch.ts
  src/admin/hooks/.gitkeep
  src/admin/pages/CreateEvent/CreateEvent.tsx
  src/admin/pages/EventManagement/EventManagement.tsx
  src/admin/types/api.ts
  src/admin/types/event.ts
  src/client/api/fetch.ts
  src/client/api/post.ts
  src/client/components/common/AuthTooltip/AuthTooltip.test.tsx
  src/client/components/common/AuthTooltip/AuthTooltip.tsx
  src/client/components/common/Carousel/Carousel.tsx
  src/client/components/common/HomeButton/HomeButton.tsx
  src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.test.tsx
  src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.tsx
  src/client/components/mainPage/InfoScreen/WordCloud.tsx
  src/client/constants/InfoData.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/FCFSEventPage/FCFSQuizSection/FCFSQuizSection.tsx
  src/client/pages/mainPage/InfoScreen/DriveSection/DriveSection.tsx
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/types/InfoScreen.ts
  src/common/assets/images/Home.png
Labels: ✨ Feature, 🎨Style

#86 [Feature] admin 참여자 목록 api 연결
  src/admin/api/fetch.ts
  src/admin/constants/.gitkeep
  src/admin/constants/constants.tsx
  src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
  src/admin/pages/RandomParticipants/RandomParticipants.tsx
  src/admin/router/router.tsx
  src/admin/types/event.ts
Labels: 📬 API

#87 [Feature] 어드민 api 연결 및 재인증 기능 적용
  public/index.html
  src/admin/api/fetch.ts
  src/admin/pages/CreateEvent/CreateEvent.tsx
  src/admin/pages/EventManagement/EventManagement.tsx
  src/admin/types/event.ts
  src/client/App.tsx
  src/client/api/fetch.ts
  src/client/components/common/HomeButton/HomeButton.tsx
  src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.tsx
  src/client/constants/api.ts
  src/client/mocks/data/AuthModal.ts
  src/client/mocks/handler/AuthModal.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/authModal/AuthModal.tsx
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/providers/ErrorBoundary.tsx
  src/client/types/AuthModal.ts
Labels: ✨ Feature

#88 [Feature] 타이머 구현
  src/client/components/mainPage/MainScreen/Timer/Timer.stories.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.test.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.tsx
  src/client/hooks/useTimer.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.test.tsx
  src/client/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.tsx
Labels: ✨ Feature

#89 [Feature] 공유 받는 페이지 구현
  public/share.css
  public/share.html
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.stories.tsx
Labels: ✨ Feature

#90 [Refactor] ErrorBoundary 추가 및 재인증 로직 추가
  package.json
  src/admin/pages/CreateEvent/CreateEvent.tsx
  src/admin/pages/EventManagement/EventManagement.tsx
  src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
  src/client/App.tsx
  src/client/api/fetch.ts
  src/client/components/common/AuthTooltip/AuthTooltip.tsx
  src/client/components/common/Glow/Glow.tsx
  src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.test.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.tsx
  src/client/constants/common.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/client/pages/authModal/AuthModal.tsx
  src/client/pages/fallbackPage/FallbackPage.tsx
  src/client/pages/mainPage/InfoScreen/ColorSection/ColorSection.tsx
  src/client/pages/mainPage/InfoScreen/InsideSection/InsideGuide.test.tsx
  src/client/pages/mainPage/InfoScreen/InsideSection/InsideGuide.tsx
  src/client/pages/mainPage/MainPage.tsx
  src/client/pages/mainPage/MainScreen/EventSelectSection/EventSelectSection.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.test.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.test.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/client/providers/ErrorBoundary.tsx
  src/client/utils/TestUtils.tsx
  src/client/utils/util.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#91 [Feature] multiple issues
  src/client/components/common/Toast/Toast.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.tsx
  src/client/constants/RandomEventData.ts
  src/client/hooks/useTimer.tsx
  src/client/pages/randomEventPage/RandomEventPage.tsx
  src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
Labels: ✨ Feature

#92 [Refactor] 에러 바운더리 시, await 추가 및 어드민 로그 페이지 생성
  src/admin/api/fetch.ts
  src/admin/pages/EventManagement/EventManagement.tsx
  src/admin/pages/LogManagement/LogManagement.tsx
  src/admin/router/router.tsx
  src/admin/types/event.ts
  src/client/App.tsx
  src/client/components/common/AuthTooltip/AuthTooltip.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.test.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.tsx
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/client/pages/fallbackPage/FallbackPage.tsx
  src/client/pages/mainPage/MainPage.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.test.tsx
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/client/router/router.tsx
Labels: ✨ Feature, 🔨 Refactor

#93 [Feature] admin 참여자 페이지 검색 구현
  src/admin/api/fetch.ts
  src/admin/components/FCFSWinnersPopup/FCFSWinnersPopup.tsx
  src/admin/components/RandomWinnersPopup/RandomWinnersPopup.tsx
  src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
  src/admin/pages/RandomParticipants/RandomParticipants.tsx
  src/admin/types/event.ts
Labels: 📬 API

#94 [Feature] 어드민 og 이미지 변경 기능 구현 및 타이머 표시 문구 변경
  src/admin/api/fetch.ts
  src/admin/pages/CreateEvent/CreateEvent.tsx
  src/admin/types/event.ts
  src/client/components/common/AuthTooltip/AuthTooltip.tsx
  src/client/components/mainPage/MainScreen/Timer/Timer.tsx
  src/client/mocks/data/AuthModal.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/mainPage/MainPage.tsx
  src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
Labels: ✨ Feature, 🔨 Refactor

#96 [Chore] 환경변수 설정
  .gitignore
  package.json
  webpack.common.js
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: ⚙ Setting

#97 [Refactor] event2 리팩토링
  src/client/api/fetch.ts
  src/client/api/post.ts
  src/client/components/randomEventPage/Option/Option.tsx
  src/client/components/randomEventPage/ProgressBar/ProgressBar.tsx
  src/client/components/randomEventPage/Roulette/Roulette.tsx
  src/client/components/randomEventPage/Tooltip/Tooltip.tsx
  src/client/constants/RandomEventData.ts
  src/client/pages/randomEventPage/RandomEventPage.tsx
  src/client/pages/randomEventPage/RandomQuizSection/RandomQuizSection.tsx
  src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/client/types/RandomEvent.ts
Labels: 🔨 Refactor

#98 [Refactor] 일부 최적화
  src/client/api/fetch.ts
  src/client/components/common/Button/Button.tsx
  src/client/pages/mainPage/InfoScreen/PerformanceSection/PerformanceSection.tsx
  src/client/pages/mainPage/MainPage.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.test.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/mainPage/NavigationBar/NavElement.tsx
  src/client/pages/mainPage/NavigationBar/NavigationBar.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  webpack.common.js
Labels: 🔨 Refactor

#101 [!HOTFIX] cors 분기 처리
  src/client/components/common/AuthTooltip/AuthTooltip.tsx
  src/client/mocks/data/AuthModal.ts
  src/client/mocks/handler/AuthModal.ts
  src/client/mocks/handler/FCFSEvent.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/client/pages/authModal/AuthModal.test.tsx
  src/client/pages/authModal/AuthModal.tsx
  src/client/pages/mainPage/MainPage.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  webpack.common.js
Labels: 🐞 BugFix

#103 [Refactor] 최적화 및 오류 수정
  public/share.css
  public/share.html
  src/client/api/fetch.ts
  src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.tsx
  src/client/pages/mainPage/InfoScreen/DriveSection/DriveSection.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
Labels: 🔨 Refactor

#104 [Feat] 어드민 배포 및 404 페이지 추가
  package.json
  src/admin/api/fetch.ts
  src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.test.tsx
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/mainPage/MainScreen/MainScreen.tsx
  src/client/router/router.tsx
  webpack.common.js
  webpack.config.js
  webpackUtil.js
Labels: 🌏 Deploy, 🔨 Refactor

#105 [Feature] event2 결과창 이슈
  public/share.html
  src/client/components/mainPage/InfoScreen/WordCloud.tsx
  src/client/constants/common.ts
  src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
  src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
  src/client/types/RandomEvent.ts
Labels: ✨ Feature, 🐞 BugFix

#106 [Refactor] 수정 사항 정리
  .idea/.name
  src/client/components/common/Carousel/Carousel.tsx
  src/client/constants/InfoData.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/client/pages/authModal/AuthModal.tsx
  src/client/pages/mainPage/InfoScreen/ColorSection/ColorSection.tsx
  src/client/pages/mainPage/InfoScreen/ConvenienceSection/ConvenienceSection.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/mainPage/MainScreen/MainScreen.tsx
  webpack.common.js
Labels: 🔨 Refactor

#107 [Feature] ux 개선, 테스트코드 수정
  src/client/components/common/Glow/Glow.tsx
  src/client/pages/FCFSEventPage/FCFSQuizSection/FCFSQuizSection.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
Labels: 🔨 Refactor

#108 [Feature] lazy 적용 및 Terser, MiniCssExtract 적용
  .DS_Store
  .idea/.name
  .idea/workspace.xml
  public/index.html
  public/share.html
  src/admin/pages/CreateEvent/CreateEvent.tsx
  src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
  src/admin/pages/RandomParticipants/RandomParticipants.tsx
  src/client/components/common/AuthTooltip/AuthTooltip.tsx
  src/client/constants/FCFSEventResultData.ts
  src/client/constants/InfoData.ts
  src/client/pages/FCFSEventPage/FCFSEventPage.tsx
  src/client/pages/FCFSEventPage/FCFSQuizSection/FCFSQuizSection.test.tsx
  src/client/pages/FCFSEventPage/FCFSQuizSection/FCFSQuizSection.tsx
  src/client/pages/FCFSEventResultPage/FCFSEventResultPage.test.tsx
  src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/client/pages/authModal/AuthModal.tsx
  src/client/pages/fallbackPage/LoadingSpinner.tsx
  src/client/pages/mainPage/InfoScreen/VideoSection/VideoSection.tsx
  src/client/pages/mainPage/MainPage.tsx
  src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
  src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
  src/client/router/router.tsx
  src/client/types/FCFSEvent.ts
  src/common/assets/svg/FCFSKeyButton.tsx
  webpack.common.js
  webpack.prod.js
  yarn.lock
Labels: ✨ Feature, 🌏 Deploy, 🔨 Refactor
