Repository softeerbootcamp4th/Team9-Podo-FE, pull requests merged in 2024-07, with the labels that each got.

#11 [hotfix] 웹팩 빌드 설정 변경
  src/App.test.js
  webpack.config.js
Labels: 🐞 BugFix

#12 hotfix: router import 경로 수정
  src/router/router.jsx
Labels: 🐞 BugFix

#14 chore: migration to typescript
  .babelrc
  eslint.config.mjs
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/pages/authModal/AuthModal.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/randomEventPage/RandomEventPage.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/router/router.tsx
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: ⚙ Setting

#16 [Style] tailwind settings
  .babelrc
  .prettierrc
  README.md
  eslint.config.mjs
  package-lock.json
  package.json
  src/App.test.js
  src/App.tsx
  src/index.tsx
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/pages/authModal/AuthModal.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/randomEventPage/RandomEventPage.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/router/router.tsx
  tailwind.config.js
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: ⚙ Setting, 🎨Style

#17 [Feature] storybook settings
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/pages/mainPage/MainPage.tsx
  tailwind.config.js
  yarn.lock
Labels: ⚙ Setting, ✅ Test

#19 [Feature] common button
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  postcss.config.js
  src/assets/images/whiteLeft.png
  src/assets/images/whiteRight.png
  src/assets/svg/Home.png
  src/components/Button.stories.tsx
  src/components/Button.tsx
  src/components/HomeButton.tsx
  src/pages/mainPage/MainPage.tsx
  src/types/images.d.ts
  webpack.config.js
  yarn.lock
Labels: ✨ Feature

#20 Feature/home button
  __mocks__/fileMock.ts
  jest.config.js
  package.json
  src/components/Button.test.tsx
  src/components/HomeButton.stories.tsx
  src/components/HomeButton.test.tsx
  src/components/HomeButton.tsx
  src/pages/mainPage/MainPage.tsx
  yarn.lock
Labels: ✨ Feature

#21 [Test] car button test
  package.json
  src/components/Button.test.tsx
  src/components/Button.tsx
  yarn.lock
Labels: ✅ Test

#22 [Feature] AuthTooltip 컴포넌트 구현
  .storybook/main.ts
  .storybook/preview.ts
  __mocks__/fileMock.ts
  jest.config.js
  package.json
  postcss.config.js
  src/App.test.js
  src/App.tsx
  src/assets/images/whiteLeft.png
  src/assets/images/whiteRight.png
  src/assets/svg/Home.png
  src/assets/svg/RefreshButton.tsx
  src/components/AuthTooltip.stories.tsx
  src/components/AuthTooltip.test.tsx
  src/components/AuthTooltip.tsx
  src/components/Button.stories.tsx
  src/components/Button.test.tsx
  src/components/Button.tsx
  src/components/HomeButton.stories.tsx
  src/components/HomeButton.test.tsx
  src/components/HomeButton.tsx
  src/pages/mainPage/MainPage.tsx
  src/router/router.tsx
  src/types/images.d.ts
  webpack.config.js
  yarn.lock
Labels: ✨ Feature, ✅ Test, 🎨Style

#24 [Feature] AuthTooltip 컴포넌트 구현
  package.json
  src/App.test.js
  src/assets/svg/RefreshButton.tsx
  src/components/AuthTooltip.stories.tsx
  src/components/AuthTooltip.test.tsx
  src/components/AuthTooltip.tsx
  src/types/images.d.ts
  webpack.config.js
  yarn.lock
Labels: ✨ Feature, ✅ Test, 🎨Style

#25 [Feature] main 이외의 페이지에 대해 컴포넌트 설계도를 따라 컴포넌트 뼈대 작성
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/FCFSEventPage/FCFSHintSection.tsx
  src/pages/FCFSEventPage/FCFSQuizSection.tsx
  src/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
  src/pages/authModal/AuthModal.tsx
  src/pages/randomEventPage/RandomEventPage.tsx
  src/pages/randomEventPage/RandomQuizSection.tsx
  src/pages/randomEventResultPage/RandomEventResultPage.tsx
  src/pages/randomEventResultPage/RandomExpectations.tsx
  src/pages/randomEventResultPage/RandomMainSection.tsx
Labels: ✨ Feature

#26 [Feat] mainPage에 대해 컴포넌트 설계도를 따라 컴포넌트 뼈대 작성
  src/assets/svg/RefreshButton.tsx
  src/pages/mainPage/ColorSection.tsx
  src/pages/mainPage/ConvenienceDescriptionItem.tsx
  src/pages/mainPage/ConvenienceSection.tsx
  src/pages/mainPage/DriveDescriptionItem.tsx
  src/pages/mainPage/DriveSection.tsx
  src/pages/mainPage/EventFooter.tsx
  src/pages/mainPage/EventHeader.tsx
  src/pages/mainPage/EventSelectOptions.tsx
  src/pages/mainPage/EventSelectSection.tsx
  src/pages/mainPage/FCFSEventSection.tsx
  src/pages/mainPage/GuideItem.tsx
  src/pages/mainPage/InfoScreen.tsx
  src/pages/mainPage/InsideSection.tsx
  src/pages/mainPage/LandingScreen.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/MainScreen.tsx
  src/pages/mainPage/NavElement.tsx
  src/pages/mainPage/NavigationBar.tsx
  src/pages/mainPage/NotificationScreen.tsx
  src/pages/mainPage/OutsideDescriptionItem.tsx
  src/pages/mainPage/OutsideSection.tsx
  src/pages/mainPage/PerformanceDescriptionItem.tsx
  src/pages/mainPage/PerformanceSection.tsx
  src/pages/mainPage/RandomEventSection.tsx
  src/pages/mainPage/Timer.tsx
Labels: ✨ Feature

#29 Feature/event2
  src/components/randomEventPage/ProgressBar/ProgressBar.stories.tsx
  src/components/randomEventPage/ProgressBar/ProgressBar.test.tsx
  src/components/randomEventPage/ProgressBar/ProgressBar.tsx
  src/pages/FCFSEventPage/FCFSEventPage.tsx
  src/pages/randomEventPage/RandomEventPage.tsx
  src/pages/randomEventPage/RandomQuizSection.tsx
  src/router/router.tsx
Labels: ✨ Feature, ✅ Test, 🎨Style
